# NOTE: This file is based on:
#https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/security/distributed-session/ds-auth/src/main/resources/application.yml

spring:
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  datasource:
    url: "jdbc:postgresql://postgres_authentication:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "validate"