# NOTE: This file is based on:
#https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/security/distributed-session/ds-auth/src/main/resources/application.yml

spring:
  spring:
    rabbitmq:
      host: rabbitmq
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  datasource:
    url: "jdbc:postgresql://postgres_authentication:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        jdbc:
          lob:  # Disables error-like log in console:
            non_contextual_creation: true #https://github.com/spring-projects/spring-boot/issues/12007
  application:
    name: authentication

