version: '3.3'

services:

  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - registry


  postgres_movies:
    image: "postgres:10"

  movies:
    build:
      context: ./movies
      dockerfile: Dockerfile
    depends_on:
      - postgres_movies
      - gateway

