version: '3.3'

services:

  redis:
    image: "redis:latest"

  postgres_authentication:
    image: "postgres:10"

  postgres_movies:
    image: "postgres:10"

  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - registry

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    depends_on:
      - postgres_authentication
      - redis
      - gateway


  movies_0:
    build:
      context: ./movies
      dockerfile: Dockerfile
    environment:
      - MOVIES_LB_ID=A
    depends_on:
      - redis
      - postgres_movies
      - gateway

  movies_1:
    build:
      context: ./movies
      dockerfile: Dockerfile
    environment:
      - MOVIES_LB_ID=B
    depends_on:
      - redis
      - postgres_movies
      - gateway

  movies_2:
    build:
      context: ./movies
      dockerfile: Dockerfile
    environment:
      - MOVIES_LB_ID=C
    depends_on:
      - redis
      - postgres_movies
      - gateway

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile