version: '3.3'

services:
  # Note that here I am using a real database.
  # Cannot use embedded H2 as done so far, because
  # all the different instances of the replicated services
  # need to work on the same data.
  #
  # All these replicated instances of "service" will use the
  # same database.
  # However, if we had other kinds of APIs here, each kind will
  # need to use their own database.
  postgres_movies:
    image: "postgres:10"

  movies:
    build:
      context: ./movies
      dockerfile: Dockerfile
    depends_on:
      - postgres_movies

