version: '3.3'

services:

  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - registry


  postgres_movies:
    image: "postgres:10"

  movies_0:
    build:
      context: ./movies
      dockerfile: Dockerfile
    environment:
      - MOVIES_ID=A
    depends_on:
      - postgres_movies
      - gateway

  movies_1:
    build:
      context: ./movies
      dockerfile: Dockerfile
    environment:
      - MOVIES_ID=B
    depends_on:
      - postgres_movies
      - gateway

  movies_2:
    build:
      context: ./movies
      dockerfile: Dockerfile
    environment:
      - MOVIES_ID=C
    depends_on:
      - postgres_movies
      - gateway