#NOTE: This file is based on:
#https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/microservice/gateway/gateway-service/src/main/resources/application.yml

spring:
  application:
    name: graphql
  rabbitmq:
    host: rabbitmq #TODO: remove if not getting to work
  datasource:
    url: "jdbc:postgresql://postgres_graphql:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:  # Disables error-like log in console:
            non_contextual_creation: true #https://github.com/spring-projects/spring-boot/issues/12007
  session:
    # specify that session tokes should be stored in Redis
    store-type: redis

  # Explicitly tell Spring to throw an exception when 404
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    add-mappings: false

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
external:  #NOTE: This is a bit verbose, as the port is the only thing that really changes. However, it makes the code cleaner
  api-base: "http://localhost:80/api/"