#NOTE: This file is based on:
#https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/microservice/gateway/gateway-service/src/main/resources/application.yml

spring:
  application:
    name: graphql
  datasource:
    url: "jdbc:postgresql://postgres_graphql:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:  # Disables error-like log in console:
            non_contextual_creation: true #https://github.com/spring-projects/spring-boot/issues/12007
  redis:
    host: redis
    port: 6379
  session:
    # specify that session tokes should be stored in Redis
    store-type: redis

  # Explicitly tell Spring to throw an exception when 404
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    add-mappings: false


eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://registry:8761/eureka/