#NOTE: This is a modified version of:
##https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/microservice/gateway/gateway-scg/src/main/resources/application.yml

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication
          uri: http://authentication:8080
          predicates:
            - Path=/api/authentication/**
          filters:
            - StripPrefix=1
        - id: graphql
          uri: http://graphql:8080
          predicates:
            - Path=/api/graphql/**
          filters:
            - StripPrefix=1
        - id: api
          uri: lb://api
          predicates:
            - Path=/api/** #api/ -> go to /users, /requests, /messages
          filters:
            - StripPrefix=1
        - id: frontend
          uri: http://frontend
          predicates:
            - Path=/**


eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
