drop table if exists director_entity;
drop table if exists director_entity_movies;
drop table if exists friend_request_entity;
drop table if exists message_entity;
drop table if exists movie_entity;
drop table if exists screening_entity;
drop table if exists user_entity;
drop table if exists user_entity_friends;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start with 1 increment by 1;
create table director_entity (id bigint not null, family_name varchar(100), given_name varchar(100), primary key (id));
create table director_entity_movies (director_entity_id bigint not null, movies_id bigint not null);
create table friend_request_entity (id bigint not null, receiver_id bigint, sender_id bigint, primary key (id));
create table message_entity (id bigint not null, creation_time timestamp, text varchar(255), receiver_id bigint, sender_id bigint, primary key (id));
create table movie_entity (id bigint not null, title varchar(150), year integer not null check (year<=2500 AND year>=1880), director_id bigint, primary key (id));
create table screening_entity (id bigint not null, available_tickets integer not null check (available_tickets>=0), room varchar(255), time timestamp, movie_id bigint, primary key (id));
create table user_entity (id bigint not null, email varchar(255), family_name varchar(255), given_name varchar(255), primary key (id));
create table user_entity_friends (user_entity_id bigint not null, friends_id bigint not null);
alter table director_entity_movies add constraint UK_nlxby8bhgbf2nqjdgw8uk5qp0 unique (movies_id);
alter table user_entity_friends add constraint UK_safhqh3hjwf34e7a64ec3ftvh unique (friends_id);
alter table director_entity_movies add constraint FKavh2hu1a1vwaf4ov8hwvahvlt foreign key (movies_id) references movie_entity;
alter table director_entity_movies add constraint FK29on5ds31atcnjgtnqhds50sc foreign key (director_entity_id) references director_entity;
alter table friend_request_entity add constraint FKk55ey5d7sb3ytrre5ac1gxgfq foreign key (receiver_id) references user_entity;
alter table friend_request_entity add constraint FKcbteq13gxvfc6dri7d5ct8r3j foreign key (sender_id) references user_entity;
alter table message_entity add constraint FKf1eboma4d9p0wlj48qwpd2ban foreign key (receiver_id) references user_entity;
alter table message_entity add constraint FKchngvnhlot2wncosjrnmd1qjp foreign key (sender_id) references user_entity;
alter table movie_entity add constraint FKbvs9legr1vasnekr8q39phwni foreign key (director_id) references director_entity;
alter table screening_entity add constraint FK5l8i3imqsj6out4on14wlj7d7 foreign key (movie_id) references movie_entity;
alter table user_entity_friends add constraint FKr4yoc9gkwyx5eo8keps65uc8e foreign key (friends_id) references user_entity;
alter table user_entity_friends add constraint FKqjftnkix11pb9h0sx4vuw4vg8 foreign key (user_entity_id) references user_entity;